### ISSUE TITLE
Does not install without `git-validate`

### ISSUE THREAD

**Issue by Granjow** [lucygilbert/json-display#7]
This package can only be installed if you also install git-validate due to the postinstall script:

```
> json-display@1.2.0 postinstall /data/workspace/mobile-escape/testarea/node_modules/json-display
> node install.js

module.js:529
    throw err;
    ^

Error: Cannot find module 'git-validate'
```

Also, I find it not so nice that it adds git hooks to **MY** git repository when I `npm install` it :D 

Apart from this, it works really nicely.

**Comment by lucygilbert** [comment]
Yeah, I'll just delete the hooks altogether I think.

**Comment by lucygilbert** [comment]
Just saw your PR, looks good, I merged it. Thank you.

**Comment by chris-hydra** [comment]
Lucy, 

Thanks for your work on this cool package - just a heads-up, `npm install json-display` still fails b/c of `git-validate` dependency:

```bash
[foo@machine dev]# npm install json-display

> json-display@1.2.0 postinstall ~/dev/node_modules/json-display
> node install.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'git-validate'
```

v. 1.2.0 package.json:
```JSON

{
  "name": "json-display",
  "version": "1.2.0",
  "description": "Accepts JSON and returns a structure of HTML elements displaying the JSON",
  "main": "json-display.js",
  "scripts": {
    "postinstall": "node install.js",
    "lint": "jshint ./**/*.js",
    "test": "karma start"
  },
  "keywords": [
    "json",
    "html",
    "formatter"
  ],
```

OS X, node v6.9.1, npm v3.10.8

**Comment by lucygilbert** [comment]
Sorry Chris. I often go a long time without checking my private repos because I'm tied up with work.

I've fixed that up in 1.2.1
